### ISSUE TITLE
Add .net support for Lambda Powertools

### ISSUE THREAD

**Issue by t1agob** [awslabs/aws-lambda-powertools#17]
**Runtime:** 
.net (C#)

**Is your feature request related to a problem? Please describe**
I have been engaged in multiple conversations with different customers using .net where they ask for best practices on how to write metrics to cloudwatch, implement tracing and logging. Immediatelly Lambda Powertools comes to my mind but support for microsoft workloads is missing. 

**Describe the solution you'd like**
I would like to have a single library that I can use to capture metrics, traces and logging at the same time that I am guaranteed that best practices are applied.

**Describe alternatives you've considered**
The current alternative right now is to use different libraries or implementing the features by ourselves which might be difficult to guarantee depending on the existing knowledge on the topic.

**If you provide guidance, is this something you'd like to contribute?**
YES.

**Additional context**
Currently all languages supported by Lambda Powertools support Core features (tracing, metrics, logging) but they have been expanded to support additional patterns and best practices. The same must be true for this implementation. 

All feature requests are more then welcome since all of us have different needs.

**Comment by Lanayx** [comment]
.NET (F#) please as well

**Comment by sliedig** [comment]
@Lanayx thanks for the feedback. For now, our focus is on C# with a view of releasing core features and additional utilities as prioritised by customer and community feedback. Will keep F# in mind though.

**Comment by ssathasivanACR** [comment]
Is the any update on this initiative. In the mean time any recommendations for an alternate library for structured logging

**Comment by t1agob** [comment]
@ssathasivanACR the project was announced in **preview** last month. Go the [project page](https://github.com/awslabs/aws-lambda-powertools-dotnet) for more details.

**Comment by ssathasivanACR** [comment]
I am using the preview option for some POCS. Any update on the GA...  The nuget package has less than 100 download (https://www.nuget.org/stats/packages/AWS.Lambda.Powertools.Logging?groupby=Version) . So  was checking in

**Comment by sliedig** [comment]
@ssathasivanACR GA is a work in progress. We are looking at a couple of new features, RFC's are being put together now and will be published soon. In the meantime feel free to ask any questions here https://github.com/awslabs/aws-lambda-powertools-dotnet
