### ISSUE TITLE
Invalid format using metrics

### ISSUE THREAD

**Issue by marcioemiranda** [awslabs/aws-lambda-powertools#26]
Hello Heitor,

I am switching all my EMF logs from ordinary prints to the metric module.

All went fine except for this one. Below is the snippet that threw the error, the error raised and the equivalent print:

**Error**
Invalid format. Error: data._aws.CloudWatchMetrics[0].Metrics[0].Unit must match pattern ^(Seconds|Microseconds|Milliseconds|Bytes|Kilobytes|Megabytes|Gigabytes|Terabytes|Bits|Kilobits|Megabits|Gigabits|Terabits|Percent|Count|Bytes\\/Second|Kilobytes\\/Second|Megabytes\\/Second|Gigabytes\\/Second|Terabytes\\/Second|Bits\\/Second|Kilobits\\/Second|Megabits\\/Second|Gigabits\\/Second|Terabits\\/Second|Count\\/Second|None)$, Invalid item: data._aws.CloudWatchMetrics[0].Metrics[0].Unit"

**using single_metric**
 with single_metric(name="invoke-rate", unit=MetricUnit.CountPerSecond, value=int(rate)) as metric:
             metric.add_namespace(name='Campaign/Orchestrator/WorkerInvokeRate')
             metric.add_dimension(name='media', value='SMS')

**ordinary print**        
print(json_dumps({
            "_aws": {
                "CloudWatchMetrics": [
                    {
                        "Namespace": "Campaign/Orchestrator/WorkerInvokeRate",
                        "Dimensions": [["media"]],
                        "Metrics": [
                            {
                                "Name": "rate",
                                "Unit": "Count/Second"
                            }
                        ],
                    }
                ],
                "Timestamp": int(datetime.now().timestamp()*1000)
            },
            "media": "SMS",
            "rate": int(rate)
            }))

**Comment by heitorlessa** [comment]
Thanks for reporting Marcio - I’ll publish a patched version later today

There’s a typo here for all “X Per Second”

https://github.com/awslabs/aws-lambda-powertools/blob/2aac986038cf9dd1b7ad3f3b7e360aac8ff0a2e4/python/aws_lambda_powertools/helper/models.py#L102

As a workaround until the patch is published, use a string as the metric
unit - **unit=“Count/Second”**

**Comment by heitorlessa** [comment]
Fixing this now, found another edge case

**Comment by heitorlessa** [comment]
Just released **0.8.1** with the fix, including additional tests that were missing.

Thank you (again) for helping out @marcioemiranda
