### ISSUE TITLE
aiohttp is now a required dependency

### ISSUE THREAD

**Issue by michaelbrewer** [awslabs/aws-lambda-powertools#31]
Even if you don't use or require aiohttp, powertools now has it as a dependency. So now projects without this already declared will fail

```
/opt/python/3.7.6/lib/python3.7/site-packages/aws_lambda_powertools/tracing/__init__.py:3: in <module>
    from aws_xray_sdk.ext.aiohttp.client import aws_xray_trace_config as aiohttp_trace_config
/opt/python/3.7.6/lib/python3.7/site-packages/aws_xray_sdk/ext/aiohttp/client.py:4: in <module>
    import aiohttp
E   ModuleNotFoundError: No module named 'aiohttp'
```

**Comment by heitorlessa** [comment]
Thanks for reporting Michael - Looking into this ASAP

**Comment by heitorlessa** [comment]
Publishing a fix in a few minutes

**Comment by michaelbrewer** [comment]
Awesome thanks. Great tool. 

FYI when using dependabot I don’t see any changelog coming through, maybe by v1 you can start generating one in the repo :)

**Comment by heitorlessa** [comment]
Just published **0.9.2** with the bugfix - Wheels took a while to generate this time.

Ha! I thought it was picking up [HISTORY file changes](https://github.com/awslabs/aws-lambda-powertools/blob/develop/python/HISTORY.md) - I'll look into it, and thanks again for the tip ;)

Let me know if that works for you @michaelbrewer

**Comment by michaelbrewer** [comment]
@heitorlessa  yes, i think @dependabot is looking for a CHANGELOG.md file. 

I can confirm that the fix is working again.

**Comment by heitorlessa** [comment]
Awesome! Thanks again for the bug report

**Comment by michaelbrewer** [comment]
@heitorlessa completely unrelated, but you might want to setup GPG signing for your your commits to github.

**Comment by heitorlessa** [comment]
In my backlog already :)
