### ISSUE TITLE
Error calling decorated function from another decorated function

### ISSUE THREAD

**Issue by cakepietoast** [awslabs/aws-lambda-powertools#32]
When decorating multiple functions with Tracer.capture_method(), a RuntimeError is thrown if one of those methods contains a call to the other as it tries to run an event loop which is already running.

The offending code is here: https://github.com/awslabs/aws-lambda-powertools/blob/develop/python/aws_lambda_powertools/tracing/tracer.py#L454

To reproduce:

```
import json
from aws_lambda_powertools.tracing import Tracer

tracer = Tracer()


@tracer.capture_method
def func_1():
    return 1

@tracer.capture_method
def func_2():
    return 2

@tracer.capture_method
def sums_values():
    return func_1() + func_2()  # Calling a decorated function from another decorated function causes an error.

def lambda_handler(event, context):
    val = sums_values()

    return {
        "statusCode": 200,
        "body": json.dumps({
            "message": val,
        }),
    }

```

**Comment by heitorlessa** [comment]
Thanks for reporting it Tom!

I created a test and reproduced it successfully. I couldn't find a reliable fix for that yet - I'll keep on trying and report back once I have some any good news

**Comment by heitorlessa** [comment]
Got it working now - I'll publish a patch in the next hour or so. need to do some tidying first

![image](https://user-images.githubusercontent.com/3340292/82124548-95f5ef00-9797-11ea-8e19-75f9bcbb6b61.png)

**Comment by heitorlessa** [comment]
hey Tom @cakepietoast  - Could you try `0.9.3` and let me know if that's also successful from your end?

Tests passed, and also tested with a deployed Lambda fn using the same code - just want to be triple sure before I commit to CHANGELOG.

**Comment by cakepietoast** [comment]
@heitorlessa working fine now, thanks for the quick fix!
