### ISSUE TITLE
CHANGELOG.* not picked up by @dependabot 

### ISSUE THREAD

**Issue by michaelbrewer** [awslabs/aws-lambda-powertools#35]
Although there is a CHANGELOG.* in the project it is not being picked up by @dependabot

It might either be that it is not in the base of the project (currently it is in a sub folder "python") or that is does not include an anchor tag at the release tag.

Otherwise adding maybe doing a `git tag` on release and creating github releases works without a  CHANGELOG.*, but it is nice have the  CHANGELOG.* in the project itself.

**Comment by heitorlessa** [comment]
Hey Michael,

Is there I can test this?

I saw I could create a root project config for dependabot in a monorepo
like, though unsure whether that’s for applications vs libraries.

If there isn’t, I’ll simply use GitHub releases as my next step.

Thanks again for the help

**Comment by michaelbrewer** [comment]
The AWS CDK is a monorepo but has only a single CHANGELOG.md at the base of the project, but of coz they do keep releases for all of the subprojects in sync. You might not want to do this when you have a Typescript implementation? Or maybe that would just be a new repo?

**Comment by heitorlessa** [comment]
I’ve done some research on automated tooling - It seems we’ll have to break
this into multiple repos, as different languages will have automated
tooling e.g Changelog, docs, etc.

e.g aws-lambda-powertools-python

For the time being, I’ll duplicate the Changelog to the project repo. I’ll
talk to other OSS maintainers to understand how they’ve solved this for
larger projects.

Thanks again for bringing this up - You’ve been a great help

**Comment by heitorlessa** [comment]
@michaelbrewer please feel free to reopen if having CHANGELOG in the root doesn't solve either

**Comment by michaelbrewer** [comment]
Sure thing, best of luck. 

I see that tools like [Standard Version](https://github.com/conventional-changelog/standard-version) is quite popular, by using a conventional commit format to help generate Changelogs and version numbers. You can even setup pre-commit hooks to formalize it. The maintainers of AWS CDK do a great job.
