### ISSUE TITLE
Combine logging and tracing ?

### ISSUE THREAD

**Issue by andyt530** [awslabs/aws-lambda-powertools#4]
Hi 

What should you put before the lambda handler to use both logging and tracing ?

I have this:

@logger_inject_lambda_context
@tracer.capture_lambda_handler
def handler(event, context)

**Comment by heitorlessa** [comment]
Hey Andy - Invert that.

Tracer ultimately runs the handler so it should be the last one —
Decorators run from bottom up

@tracer.capture_lambda_handler
@logger...
def handler(event, context):
    ...

I’ll add an example in 2 weeks (in the middle of something) — Let me know
if it doesn’t work and I can help

**Comment by heitorlessa** [comment]
cc @andyt530 in case you missed the response :)

**Comment by heitorlessa** [comment]
Resolving as I haven't heard back from Andy. Created an explicit task to add a Lambda function as an example
